### ISSUE TITLE
Unintended TS behaviour with asChild + cva usage?

### ISSUE THREAD

**Issue by mastondzn** [gregberge/twc#12]
If you use [the cva pattern as documented](https://react-twc.vercel.app/docs/guides/adapting-based-on-props#use-with-cva) you will get a TS error if you also try to pass asChild to the composed component (still does work though), i assume this not intended 🤔

```tsx
// ts error if trying to use asChild with this Button
const Button = twc.button<ButtonProps>(({ variant }) => button({ variant }))

// doing this makes it work as expected
const Button = twc.button<ButtonProps & { asChild?: boolean }>(({ variant }) => button({ variant }))
```

edit: after checking how it works a little bit more it seems like using this generic is very unsafe, imo it doesnt really makes sense how it works rn:

```tsx
const Div = twc.div<{test: boolean}>``;
// cannot even pass children
<Div test>
	<Anything/>
</Div>
```
in my opinion this generic should not work like this at all, i will attempt to fix this and explain my reasoning a little bit more in a pr and see if you like it

**Comment by gregberge** [comment]
I close it, We won't do this for reasons in #13.
