### ISSUE TITLE
Incorrect exports: Could not find a declaration file for module 'react-twc'

### ISSUE THREAD

**Issue by gabrielelpidio** [gregberge/twc#2]
## 🐛 Bug Report
Could not find a declaration file for module 'react-twc'. 'stackblitz:/node_modules/react-twc/dist/index.mjs' implicitly has an 'any' type.
There are types at 'stackblitz:/node_modules/react-twc/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-twc' library may need to update its package.json or typings.(7016)

![image](https://github.com/gregberge/twc/assets/30420087/39f52a1c-c110-4d69-9321-43883df1f9a3)

## To Reproduce

Install the library within a typescript project: [Stackblitz](https://stackblitz.com/edit/stackblitz-starters-tbod5x?description=The%20React%20framework%20for%20production&file=app%2Flayout.tsx,app%2Fpage.tsx&title=Next.js%20Starter)

## Expected behavior

To import the correct typings, it should be solved by changing the exports in the package.json

## Link to repl or repo (highly encouraged)

[Stackblitz](https://stackblitz.com/edit/stackblitz-starters-tbod5x?description=The%20React%20framework%20for%20production&file=app%2Flayout.tsx,app%2Fpage.tsx&title=Next.js%20Starter)

## Run `npx envinfo --system --binaries --npmPackages twc,react,react-dom --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 5.0 undefined
 - CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 0 Bytes / 0 Bytes
 - Shell: 1.0 - /bin/jsh
## Binaries:
 - Node: 18.18.0 - /usr/local/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.4.2 - /usr/local/bin/npm
 - pnpm: 8.10.5 - /usr/local/bin/pnpm
## npmPackages:
 - react: 18.2.0 => 18.2.0 
 - react-dom: 18.2.0 => 18.2.0
```

**Comment by gregberge** [comment]
Fixed in #3, thanks.

**Comment by viczam** [comment]
I'm still seeing this on 1.0.1 and nextjs.

**Comment by gregberge** [comment]
@viczam it's now 100% fixed.

**Comment by viczam** [comment]
> @viczam it's now 100% fixed.

I've noticed that and I've been using it already and it's awesome. Great job!
