### ISSUE TITLE
`react-twc` with `@radix-ui/react-accordion` - `collapsible` prop does not respect conditional `type="single"`

### ISSUE THREAD

**Issue by scythewyvern** [gregberge/twc#24]
## 🐛 Bug Report

Hi! Thank you for this amazing lib,

I've encountered an issue when integrating `react-twc` with `@radix-ui/react-accordion`. According to the [Radix Accordion documentation](https://www.radix-ui.com/primitives/docs/components/accordion#root), the `collapsible` property should only be available when the `type` prop is set to `single`. However, it seems that this conditional logic is not being enforced when using `react-twc` to wrap the Accordion component.

Here's a snippet of how I'm using the library:

```jsx
import * as AccordionPrimitive from "@radix-ui/react-accordion";
import { twc } from "react-twc";

const Accordion = twc(AccordionPrimitive.Root)`py-2`;

export default function App() {
  return (
    <div className="App">
      {/* Should only allow `collapsible` when `type="single"` */}
      <Accordion type="single" collapsible>
                                 ^ here is type error
        {/* ... */}
      </Accordion>

      {/* Default usage without twc wrapper works as expected */}
      <AccordionPrimitive.Root type="single" collapsible>
        {/* ... */}
      </AccordionPrimitive.Root>
    </div>
  );
}
```

## To Reproduce

CodeSandbox: https://codesandbox.io/p/sandbox/twc-radix-qz36h7

## Expected behavior:
The `collapsible` prop should be conditional on the `type` prop being `single`, similar to how it works with the standard `@radix-ui/react-accordion` component usage.

Could you please look into this? It would be great to have `react-twc` enforce the same conditional prop logic as the original library or provide guidance on how to implement it.

Thank you for your assistance!

**Comment by gregberge** [comment]
@scythewyvern the `className` prop conflict, so I omit it from the type, when I do that, the type is a little corrupted. So for this case, you have to specify explicit props, then the `className` will be the one provided by Radix. You can't have both a custom `className` and the conditional type for `type` prop.

```ts
import * as React from "react";
import * as AccordionPrimitive from "@radix-ui/react-accordion";
import { twc } from "react-twc";

const Accordion = twc(AccordionPrimitive.Root)<React.ComponentProps<typeof AccordionPrimitive>>`py-2`;
```
