### ISSUE TITLE
Incorrect CSS conflicts with Tailwind CSS IntelliSense extension

### ISSUE THREAD

**Issue by rickyzhangca** [gregberge/twc#25]
## 🐛 Bug Report

With Tailwind CSS IntelliSense extension installed, styles would be seen as conflicting with each other even though they are for separate components.

<img width="628" alt="image" src="https://github.com/gregberge/twc/assets/16908811/f089292e-9f07-4260-9d1f-d9f5aac4fe66">

I am migrating from https://github.com/MathiasGilson/Tailwind-Styled-Component, it does not have this problem if it helps

## To Reproduce

1. follow https://react-twc.vercel.app/docs/getting-started to set up
2. write 2 components with some overlapping style rules in one file

## Expected behavior

They should not be seen as a CSSConclict

**Comment by gregberge** [comment]
Hello @rickyzhangca, fixed, sorry, please upgrade your autocompletions with that:

```json
[
  "twc\\.[^`]+`([^`]*)`",
  "twc\\(.*?\\).*?`([^`]*)",
  ["twc\\.[^`]+\\(([^)]*)\\)", "(?:'|\"|`)([^']*)(?:'|\"|`)"],
  ["twc\\(.*?\\).*?\\(([^)]*)\\)", "(?:'|\"|`)([^']*)(?:'|\"|`)"]
]
```
