### ISSUE TITLE
Add support for svg element

### ISSUE THREAD

**Issue by jahirfiquitiva** [gregberge/twc#27]
## 🚀 Feature Proposal

Please add support to style the `svg` element.

![Shot 2023-12-26 at 20 00 56@2x](https://github.com/gregberge/twc/assets/10360816/b4da6852-eb2d-4bae-96a0-6ccc2dd81b3f)

**Comment by jahirfiquitiva** [comment]
Or any html element, really 😅

**Comment by gregberge** [comment]
It was a typing problem, solved in #28.

**Comment by jahirfiquitiva** [comment]
oh, great! Thanks @gregberge
