### ISSUE TITLE
Add ShouldForwardProp option to the twc function

### ISSUE THREAD

**Issue by elmarvr** [gregberge/twc#29]
## 🚀 Feature Proposal

Add ShouldForwardProp option to the twc function

## Motivation

I don't want to use the prefixed props syntax

## Example

twc.div(({ variant}) => buttonVariants({ variant} ) , (prop) => prop === "variant"))

**Comment by gregberge** [comment]
You can use https://react-twc.vercel.app/docs/api-reference#createtwc to do that.

**Comment by elmarvr** [comment]
But isn't it awkward to use the factory for individual components? And what if you also need some global config? Or are you suggesting adding all the different variant keys in a global createTwc?

**Comment by gregberge** [comment]
@elmarvr I will think about a way to customize it locally.

**Comment by gregberge** [comment]
@elmarvr thanks for your suggestion, it is now possible: https://react-twc.vercel.app/docs/guides/adapting-based-on-props#customize-transient-props
