### ISSUE TITLE
Is it possible to use styled-components?

### ISSUE THREAD

**Issue by mthmcalixto** [gregberge/twc#34]
@gregberge  I was thinking, is this project possible to use like we use styled-components?

For example:

```tsx
const List = styled.ul`
  display: inline-block;

  & > li > a {
    color: red;
  }
`;
```

Twc?
```tsx
const List = twc.ul`
  inline-block

  & > li > a {
    text-red-500
  }
`;
```

**Comment by gregberge** [comment]
Hi @mthmcalixto, no twc is not a CSS in JS library, it is a class component creator.
