### ISSUE TITLE
twc(SomeRadixComponent) => asChild won't work as expect

### ISSUE THREAD

**Issue by Mingx94** [gregberge/twc#8]
## 🐛 Bug Report

twc(SomeRadixComponent)`` component => asChild won't work as expect

## To Reproduce
```jsx
const HoverCardContent = twc(
  HoverCard.Content
)`data-[side=bottom]:animate-slideUpAndFade data-[side=right]:animate-slideLeftAndFade data-[side=left]:animate-slideRightAndFade data-[side=top]:animate-slideDownAndFade w-[300px] rounded-md bg-white p-5 shadow-[hsl(206_22%_7%_/_35%)_0px_10px_38px_-10px,hsl(206_22%_7%_/_20%)_0px_10px_20px_-15px] data-[state=open]:transition-all`

const Hover = () => {
  ...
  return (
    ...
    <HoverCardContent
      className="bg-cyan-200 w-[300px] h-[300px]"
      sideOffset={5}
      asChild
    >
      {/* hover card won't work */}
      <div>
         ....
      </div>
    </HoverCardContent>
    ...
  )
}

```

## Expected behavior

should work with radix components

## Link to repl or repo (highly encouraged)

https://codesandbox.io/p/devbox/react-twc-hover-card-9t6tzc

## Run `npx envinfo --system --binaries --npmPackages twc,react,react-dom --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 14.1.1
 - CPU: (8) arm64 Apple M1
 - Memory: 84.41 MB / 8.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
 - npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
 - pnpm: 7.30.0 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
## npmPackages:
 - react: ^18.2.0 => 18.2.0 
 - react-dom: ^18.2.0 => 18.2.0 
 - react-twc: ^1.0.1 => 1.0.1 
```

**Comment by gregberge** [comment]
There was an error in your code: 

![CleanShot 2023-12-22 at 13 39 34@2x](https://github.com/gregberge/twc/assets/266302/380a687d-cf1c-4ae3-9600-759008d0a9ec)

I fixed it and it works: https://codesandbox.io/p/devbox/react-twc-hover-card-forked-748mcw?file=%2FApp.jsx%3A30%2C24

**Comment by Mingx94** [comment]
oh sorry,
i mean, when i use twc with radix component
the asChild will replace the original radix component asChild behavior

I've changed my [example](https://codesandbox.io/p/devbox/react-twc-hover-card-9t6tzc?file=%2FApp.jsx%3A4%2C1)
